RELATED: RAIL-5217 Use correct documentation links
gooddata/gooddata-ui-apidocs pull request #19
Opened 2023-11-30 14:45 UTC by pbenes

2023-11-30 14:46 UTC, gdgate commented
Build succeeded (check pipeline).

2023-12-04 08:18 UTC, ivanmjartan approved these changes

2023-12-04 08:20 UTC, kandl approved these changes
LGTM

2023-12-04 08:24 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-apidocs-gate-PR19

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2023-12-04 08:28 UTC, Mara3l requested changes

2023-12-04 08:28 UTC, Mara3l commented on js/generateVersionsTable.js
> +        var corrected = majorAndMinorVersion === "9.0" ? "9.1" : majorAndMinorVersion;
Please erase this line, as we do actually support 9.0, but it is hidden in the dropdown menu. The link should still be valid.

2023-12-04 08:30 UTC, ghost commented
Build succeeded (check pipeline).

2023-12-04 08:34 UTC, Mara3l approved these changes

2023-12-04 08:36 UTC, ivanmjartan approved these changes

2023-12-04 08:37 UTC, ivanmjartan approved these changes

2023-12-04 08:39 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-apidocs-gate-PR19

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2023-12-04 08:39 UTC, merged

2023-12-04 08:39 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-sonarqube-scan-zuul-gate/30/ : SUCCESS in 1m 40s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-fossa-scanning-zuul/2/ : SUCCESS in 2m 04s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-apidocs-merge-compliance-check/25/ : SUCCESS in 10s